-- Client migration step 3: insert 49 unique companies
INSERT INTO clients (client_name, formatted_client_name, tla) VALUES
  ('Arralyze', 'Arralyze [ARR]', 'ARR'),
  ('Asymmetrex', 'Asymmetrex [ASY]', 'ASY'),
  ('Azure Biosystems', 'Azure Biosystems [AZB]', 'AZB'),
  ('Beckman Coulter Life Sciences', 'Beckman Coulter [BCS]', 'BCS'),
  ('BMG Labtech', 'BMG LABTECH [BMG]', 'BMG'),
  ('Boster Bio', 'Boster Bio [BOB]', 'BOB'),
  ('Bio-Techne', 'Bio-techne [BTN]', 'BTN'),
  ('Collaborative Drug Discovery', 'Collaborative Drug Discovery [CDD]', 'CDD'),
  ('Covaris', 'Covaris [COV]', 'COV'),
  ('Cytomos', NULL, 'CYT'),
  ('DeNovix Inc.', 'DeNovix [DEN]', 'DEN'),
  ('enGenes', 'enGenes [ENG]', 'ENG'),
  ('Eppendorf', 'Eppendorf [EPP]', 'EPP'),
  ('Fios Genomics Ltd.', 'Fios Genomics Ltd [FIO]', 'FIO'),
  ('GenoFAB', 'GenoFAB [GFB]', 'GFB'),
  ('GrubSEO', 'GrubSeo (Joe Trewick) [GRB]', 'GRB'),
  ('Hamamatsu', 'Hamamatsu [HAM]', 'HAM'),
  ('Hamilton', 'Hamilton [HTN]', 'HTN'),
  ('Integrated DNA Technologies', 'Integrated DNA Technologies [IDT]', 'IDT'),
  ('Levitas', 'Levitas [LEV]', 'LEV'),
  ('LGC, Biosearch Technologies', 'LGC Biosearch Technologies [LGC]', 'LGC'),
  ('Leica Microsystems', 'Leica Microsystems [LMS]', 'LMS'),
  ('Luminex Corporation', 'Luminex Corporation [LUM]', 'LUM'),
  ('Mabtech', 'Mabtech [MAB]', 'MAB'),
  ('Miltenyi', 'Miltenyi [MLB]', 'MLB'),
  ('Molecular Machines & Industries', 'Molecular Machines & Industries [MMI]', 'MMI'),
  ('Merck Millipore Sigma', 'Merck | Millipore Sigma [MMS]', 'MMS'),
  ('N6', NULL, 'N6T'),
  ('Olink', 'Olink [OLK]', 'OLK'),
  ('Ossila Ltd.', 'Ossila Ltd [OOS]', 'OOS'),
  ('PartitionBio', 'PartitionBio [PAR]', 'PAR'),
  ('Plasmidsaurus', 'Plasmidsaurus [PLA]', 'PLA'),
  ('Promega', 'Promega [PRM]', 'PRM'),
  ('Proteintech', 'Proteintech [PRO]', 'PRO'),
  ('Qiagen', 'Qiagen [QIA]', 'QIA'),
  ('Rainin (Mettler Toledo)', 'Rainin (Mettler Toledo) [RAI]', 'RAI'),
  ('Sartorius', 'Sartorius [SAR]', 'SAR'),
  ('Scale Bioscience', '10x Genomics [10x] (( prev. Scale Biosciences [SCA] ))', 'SCA'),
  ('Thermo Fisher Scientific', 'Thermo Fisher Scientific [TFS]', 'TFS'),
  ('TissueGnostics', 'TissueGnostics GMBH [TGN]', 'TGN'),
  ('Tomocube Inc', 'Tomocube [TOM]', 'TOM'),
  ('Twist Bioscience', 'Twist Bioscience [TWI]', 'TWI'),
  ('Unchained Labs', 'Unchained Labs [UNC]', 'UNC'),
  ('Vector Builder', 'VectorBuilder [VEB]', 'VEB'),
  ('Volta Labs Inc', 'Volta Labs Inc [VLT]', 'VLT'),
  ('Wasteless Bio', 'Wasteless Bio [WAS]', 'WAS'),
  ('Yokogawa', 'Yokogawa [YOK]', 'YOK'),
  ('Carl Zeiss Microscopy GmbH', 'Zeiss [ZEI]', 'ZEI'),
  ('Zymo Research', 'Zymo [ZYM]', 'ZYM');
