-- Client migration step 4: insert 85 client codes
INSERT INTO bsb_client_codes (
    bsb_client_code, client_id,
    primary_contact, primary_contact_email,
    other_people_in_client_code, payment_terms, po_required,
    client_billing_contact, client_billing_email, client_billing_address, notes
)
SELECT
    v.bsb_client_code, c.id,
    v.primary_contact, v.primary_contact_email,
    v.other_people, v.payment_terms, v.po_required,
    v.billing_contact, v.billing_email, v.billing_address, v.notes
FROM (VALUES
    ('ARR001', 'ARR', 'Margaryta Molibozhenko', 'm.molibozhenko@lpkf.com', NULL, 'NET 14 DAYS', 'No', 'Margaryta Molibozhenko', 'm.molibozhenko@lpkf.com', 'LPKF Laser & Electronics SE Osteriede 7 D-30827 Garbsen', NULL),
    ('ASY001', 'ASY', 'James Sherley', 'jsherley@asymmetrex.com', NULL, 'NET 14 DAYS', 'No', 'James Sherley', 'jsherley@asymmetrex.com', '39 Sheridan St. Boston, MA 02130', NULL),
    ('AZB001', 'AZB', 'Sia Ghazvini', 'sghazvini@azurebiosystems.com', 'Lisa Valdin, Jade Fee', 'NET 14 DAYS', 'Yes', 'Connie Chan', 'connie.chan@azurebiosystems.com', '6747 SIERRA COURT SUITE A-B DUBLIN, CA 94568', NULL),
    ('BCS001', 'BCS', 'Martijn Meeuwissen', 'mcmeeuwissen@beckman.com', 'Markus Kaymer', 'NET 30 DAYS', 'Yes', 'Markus Kaymer', 'mkaymer@beckman.com', 'Beckman Coulter GmbH Europark Fichtenhain B 13 47807 Krefeld Germany', NULL),
    ('BMG001', 'BMG', 'Markus Hartmann', 'markus.hartmann@bmglabtech.com', NULL, 'NET 20 DAYS', 'No', 'Markus Hartmann', 'markus.hartmann@bmglabtech.com', 'Allmendgruen 8 77799 Ortenberg Germany', NULL),
    ('BOB001', 'BOB', 'CJ Xia', 'boster@bosterbio.com', NULL, 'NET 14 DAYS', 'No', 'CJ Xia', 'boster@bosterbio.com', '3942 Valley Ave Ste B Pleasanton CA 94566', NULL),
    ('BTN001', 'BTN', 'Justyna Zaborowska', 'justyna.zaborowska@bio-techne.com', NULL, 'NET 14 DAYS', 'Yes', 'Justyna Zaborowska', 'justyna.zaborowska@bio-techne.com', 'Route de Lully 5C, 1131 Tolochenaz, Switzerland', NULL),
    ('BTN002', 'BTN', 'Jessica Slack', NULL, 'Helly Pimentel', NULL, NULL, NULL, NULL, NULL, NULL),
    ('CDD001', 'CDD', 'Joshua Zhang', 'joshua.zhang@collaborativedrug.com', NULL, 'NET 30 DAYS', 'No', 'Joshua Zhang', 'joshua.zhang@collaborativedrug.com', 'Collaborative Drug Discovery, 1633 Bayshore Hwy, Suite 342, Burlingame, CA 94010', NULL),
    ('CDD002', 'CDD', 'Abraham Wang', 'awang@collaborativedrug.com', 'Mariana', 'NET 30 DAYS', 'No', 'Abraham Wang', 'awang@collaborativedrug.com', '1633 Bayshore Hwy #342, Burlingame, CA 94010 USA', NULL),
    ('COV001', 'COV', 'Kate Meola', 'kmeola@covaris.com', 'Bruce Sidilau', 'NET 30 DAYS', 'No', 'Bruce Sidilau', 'accounting@covaris.com', '14 GILL STREET, UNIT H WOBURN MA 01801-1721', NULL),
    ('CYT001', 'CYT', 'Mike Hughson', 'mike.hughson@cytomos.com', 'Fiona Bellot - fiona.bellot@cytomos.com', 'NET 14 DAYS', 'No', 'Mike Hughson', 'mike.hughson@cytomos.com', 'Cytomos Ltd 13 Melville Street Edinburgh EH3 7PE', NULL),
    ('DEN001', 'DEN', 'Andrew Jones', 'andrew.jones@denovix.com', NULL, 'NET 14 DAYS', 'No', 'Andrew Jones', 'andrew.jones@denovix.com', 'DeNovix Inc. 3411 Silverside Rd Hanby Building Wilmington, DE 19810 USA', NULL),
    ('ENG001', 'ENG', 'Juergen Mairhofer', 'juergen.mairhofer@engenes.cc', 'Ophelia Gevaert, Peter Hacker', 'NET 14 DAYS', 'No', 'Peter Hacker please cc Katarina Kostolanska', 'peter.hacker@engenes.cc   katarina.kostolanska@engenes.cc', 'enGenes Biotech GmbH Muthgasse 11/2/1 1190 Vienna Austria', NULL),
    ('EPP001', 'EPP', 'Florence de la Grange', 'delagrange.f@eppendorf.fr', 'Lena Andersen', 'NET 14 DAYS', 'Yes', 'Lena Andersen', 'andersen.l@eppendorf.dk', 'Eppendorf France SAS 2 à 6 rue du Château d’Eau 78360 Montesson, France', NULL),
    ('FIO001', 'FIO', 'Breige McBride', 'Breige.McBride@fiosgenomics.com', NULL, 'NET 14 DAYS', 'No', 'Breige McBride', 'Breige.McBride@fiosgenomics.com', 'Fios Genomics Ltd Biocube 1,13 Little France Road Edinburgh, Scotland, EH16 4UX', NULL),
    ('GFB001', 'GFB', 'Jean Peccoud', 'peccoud@genofab.com', NULL, 'NET 30 DAYS', 'No', 'Jean Peccoud', 'peccoud@genofab.com', 'GenoFAB, Inc., 2519 S Shields St. Suite 1K #558, Fort Collins CO 80526', NULL),
    ('GRB001', 'GRB', 'Joe Trewick', 'joe@grubseo.uk', NULL, 'NET 14 DAYS', 'No', 'Joe Trewick', 'joe@grubseo.uk', 'Joe Trewick, 9 The Waterhouse, 87a Pinstone Street, Sheffield, South Yorkshire, S1 2HJ', NULL),
    ('HAM001', 'HAM', 'Georgia Ramsden', 'georgia.ramsden@hamamatsu.eu', NULL, 'NET 14 DAYS', 'No', 'Marcoms', 'marcom@hamamatsu.eu', 'Hamamatsu Photonics Europe, Arzbergerstr. 10, D- 82211 Herrsching, GERMANY, VAT Number: DE273700584', NULL),
    ('HTN001', 'HTN', 'Arianna Morosetti', 'AMorosetti@hamilton.ch', 'Meagan Callis - meagan.callis@hamiltoncompany.com', 'NET 14 DAYS', 'No', 'Arianna Morosetti', 'AMorosetti@hamilton.ch', 'Via Crusch 8 7402 Bonaduz Switzerland', NULL),
    ('IDT001', 'IDT', 'Halit Babucci', 'hbabucci@idtdna.com', 'Clotilde Teiling', 'NET 30 DAYS', 'No', 'Halit Babucci', 'hbabucci@idtdna.com', 'Integrated DNA Technologies UK, Ltd London City Point 1 Ropemaker Street London, EC2Y 9HT United Kingdom VAT number:  GB933529807', NULL),
    ('LEV001', 'LEV', 'Marcia Ruggio', 'marcia.ruggio@levitasbio.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
    ('LGC001', 'LGC', 'Franziska Sommerfeld', 'Franziska.Sommerfeld@lgcgroup.com', NULL, 'NET 60 DAYS', 'Yes', 'Accounts Payable', 'accountspayable.uk@lgcgenomics.com', 'Accounts Payable, LGC Genomics Limited, Queens Road, Teddington, Middlesex, TW11 0LY', NULL),
    ('LGC002', 'LGC', 'Abbey Boswell', 'Abby.Boswell@lgcgroup.com', NULL, 'NET 14 DAYS', 'No - but check for next order', 'Abbey Boswell', 'Abbey Boswell', 'LCG-Biosearch-MDx Queens Road, Teddington, Middlesex, TW11 0LY', NULL),
    ('LGC003', 'LGC', 'Tanika Mei', 'Tanika.Mei@lgcgroup.com', NULL, 'NET 14 DAYS', 'No - but check for next order', 'Tanika Mei', 'Tanika.Mei@lgcgroup.com', 'LCG-Biosearch-MDx Queens Road, Teddington, Middlesex, TW11 0LY', NULL),
    ('LMS001', 'LMS', 'Jo Fallowfield', 'jo.fallowfield@leica-microsystems.com', 'Benjamin Feldbusch, Sarah Piper, Christine Ludwig, Maria Zweig, Anne-Kathrin Heussinger', 'NET 30 DAYS (2nd of the next month plus 30 days)', 'Yes', 'Benjamin Feldbusch', 'FinanceServiceCenter.UK@leica-microsystems.com       Benjamin.Feldbusch@leica-microsystems.com', 'Leica Microsystems (UK) Ltd Larch House Woodlands Business Park Breckland Linford Wood Milton Keynes, MK14 6FG United Kingdom', 'Leica Microsystems GmbH Ernst-Leitz-Strasse 17-37 35578 Wetzlar Germany'),
    ('LMS002', 'LMS', 'Betty Yuen-Torres', 'betty.yuen-torres@leica-microsystems.com', NULL, 'NET 30', 'Yes', 'Accounts Payable', 'fsc@leica-microsystems.com', 'Leica Microsystems GmbH, Ernst-Leitz-Straße 17 - 37, D-35578 Wetzlar', 'NO LONGER IN USE, LEICA ALL UNDER LMS001'),
    ('LUM001', 'LUM', 'Marcha van der Steen', 'mvandersteen@luminexcorp.com', NULL, 'NET 30 DAYS', 'No', 'Accounting', 'accounting.benelux@diasorin.it', 'DiaSorin SA/NV, Reitscheweg 1-7, 5232 BX ‘s-Hertogenbosch, The Netherlands', NULL),
    ('MAB001', 'MAB', 'Jens Gertow', 'jens.gertow@mabtech.com', NULL, 'NET 60 DAYS* for Q4 invoice - revisit in future', 'No', 'Jens Gertow', 'jens.gertow@mabtech.com', 'Augustendalstorget 9 SE-131 52 Nacka Strand SWEDEN', NULL),
    ('MLB001', 'MLB', 'Luigi Prisco', 'luigip@miltenyi.com', 'Jana Soyka, Guruchandar Arulmozhivarman, Isabelle Haake', 'NET 30 DAYS', 'No', 'Jana Soyka                          Christian Hoffmann', 'janas@miltenyi.com                       Accounts_Payable_BergGL@miltenyi.com                         christianhof@miltenyi.com', 'Friedrich-Ebert-Str. 68 51429 Bergisch Gladbach Germany', NULL),
    ('MLB002', 'MLB', 'Michael Sturges', 'michaelstu@miltenyi.com', 'Julie Cole, Byron Hartmann, Evihn Vaszily', 'NET 14 DAYS', 'Yes', 'Julie Cole', 'julieco@miltenyi.com', 'Accounts Payable  1201 Clopper Rd  Gaithersburg, MD 20878', NULL),
    ('MLB003', 'MLB', 'Isabelle Haake', 'isabelleh@miltenyi.com', 'friederikef@miltenyi.com', 'NET 30 DAYS', 'Yes', 'Christian Hoffmann', 'Accounts_Payable_BergGL@miltenyi.com', 'Miltenyi Biotec B.V. & Co. KG Friedrich-Ebert-Straße 68 51429 Bergisch Gladbach Deutschland', NULL),
    ('MMI001', 'MMI', 'Martin Breitkreuz', 'breitkreuz@molecular-machines.com', NULL, 'NET 14 DAYS', 'No', 'Martin Breitkreuz', 'breitkreuz@molecular-machines.com', 'Molecular Machines & Industries GmbH Breslauer Straße 2 85386 Eching Germany', NULL),
    ('MMS001', 'MMS', 'Danielle Pepin', 'danielle.pepin@milliporesigma.com', NULL, 'NET 60 DAYS', 'Yes', 'Accounts Payable', 'usap.invoices@milliporesigma.com', '400 SUMMIT DR, BURLINGTON MA 01803, USA', NULL),
    ('MMS002', 'MMS', 'Stacey McDonald', 'stacey.mcdonald@milliporesigma.com', NULL, 'NET 60 DAYS', 'Yes', 'Stacey McDonald', 'stacey.mcdonald@milliporesigma.com', 'Sigma-Aldrich Co., LLC 3050 Spruce street, SAINT LOUIS MO 63103 United States', NULL),
    ('MMS003', 'MMS', 'Joanna Sitek', 'joanna.sitek@merckgroup.com', NULL, 'NET 60 DAYS', 'Yes', 'Joanna Sitek', 'de.invoices@merckgroup.com', 'Merck Life Science KGaA, Frankfurter Str. 250, 64279 Darmstadt', NULL),
    ('MMS004', 'MMS', 'Kelley Euchner', 'Kelley.euchner@milliporesigma.com', NULL, 'NET 60 days', 'Yes', 'Sigma-Aldrich Co., LLC', 'apinvoices@merckgroup.com', '1 Technology Place, ROCKLAND MA, 02370, USA', NULL),
    ('MMS005', 'MMS', 'Dean Orman', 'dean.orman@milliporesigma.com', NULL, 'NET 60 DAYS', 'Yes', 'Dean Orman', 'usap.invoices@milliporesigma.com                   dean.orman@milliporesigma.com', 'Sigma-Aldrich Co., LLC 400 SUMMIT DR BURLINGTON MA 01803 USA', NULL),
    ('MMS006', 'MMS', 'Jaspreet Kaur-Nandra', 'jaspreet.kaur-nandra@merckgroup.com', 'Naima Dellali', 'NET 60 DAYS', 'Yes', 'Accounts Department', 'ap.de.invoices@merckgroup.com', 'Merck Life Science KGaA, Frankfurter Str. 250, 64279 Darmstadt', NULL),
    ('MMS007', 'MMS', 'Martin Seidensticker', 'martin.seidensticker@merckgroup.com', NULL, 'NET 60 DAYS', 'Yes', 'Purchasing department', 'Purchasing_Indirect_DE@merckgroup.com', 'Merck Life Science KGaA Frankfurter Straße 250 64279 Darmstadt Germany', NULL),
    ('MMS008', 'MMS', 'Imke Koehler', 'imke.koehler@merckgroup.com', NULL, 'NET 60 DAYS', 'Yes', 'Purchasing department', 'de.invoices@merckgroup.com', 'Merck Life Science KGaA Frankfurter Straße 250 64279 Darmstadt Germany', NULL),
    ('MMS009', 'MMS', 'Maryse Sadoine', 'maryse.sadoine@merckgroup.com', NULL, 'NET 60 DAYS', 'Yes', 'FourHealth', 'PurchaseLedger@four.agency', 'The Hickman Building 2 Whitechapel Road London E1 1FX', NULL),
    ('N6T001', 'N6T', 'Jenny Alfrey', 'jenny@n6tec.com', NULL, 'NET 14 DAYS', NULL, NULL, NULL, NULL, NULL),
    ('OLK001', 'OLK', 'Aleksandra (Sasha) Savina', 'aleksandra.savina@olink.com', NULL, 'NET 60 DAYS', 'No', NULL, 'ap@olink.com', 'Salagatan 16F, SE-753 30 Uppsala, Sweden', NULL),
    ('OOS001', 'OOS', 'Caitlin Ryan', 'c.ryan@ossila.com', NULL, 'NET 14 DAYS', 'No', 'Caitlin Ryan', 'c.ryan@ossila.com', 'Ossila Ltd, Solpro Business Park Windsor St, Sheffield, UK S4 7WB', NULL),
    ('PAR001', 'PAR', 'Craig Smith', 'c.smith@partitionbio.co.uk', NULL, 'NET 30 DAYS', 'Yes', 'Caroline Orros', 'Accounts@partitionbio.co.uk', 'PartitionBio Ltd Suite 14, Science Village Chesterford Research Park Little Chesterford CB10 1XL', NULL),
    ('PLA001', 'PLA', 'Chelsea Jimenez', 'chelsea.jimenez@plasmidsaurus.com', 'Luke Hickey - luke.hickey@plasmidsaurus.com', 'NET 14 DAYS', 'No', 'Chelsea Jimenez', 'chelsea.jimenez@plasmidsaurus.com', '288 E Live Oak Ave Ste A250 Arcadia, CA. 91006 USA', NULL),
    ('PRO001', 'PRO', 'Austin Marshall', 'austin@ptglab.com', NULL, 'NET 14 DAYS', 'No', 'Austin Marshall', 'austin@ptglab.com', '5500 Pearl St Suite 400 Rosemont, IL 60018', NULL),
    ('PRO002', 'PRO', 'Poppy Nathan', 'poppy@ptglab.com', 'Amy Turner', 'NET 14 DAYS', 'No', 'Poppy Nathan', 'poppy@ptglab.com', 'Proteintech Europe Transmission, 6 Atherton Street Manchester M3 3GS', NULL),
    ('PRM001', 'PRM', 'Michele Arduengo', 'michele.arduengo@promega.com', NULL, 'NET 14 DAYS', 'No', 'Accounts Payable', 'ap@promega.com', 'Promega Corporation, 2800 Woods Hollow Road, Madison, WI 53711 USA', NULL),
    ('QIA001', 'QIA', 'Ewa Wlazlo', 'ewa.wlazlo@qiagen.com', 'Natalia Skupien, Stephanie Klauke', 'NET 30 DAYS', 'Yes', 'Stephanie Klauke', 'scanning.de@qiagen.com', 'QIAGEN GmbH Qiagen Strasse 1 40724 Hilden Germany', NULL),
    ('QIA002', 'QIA', 'Raissa Pietersen', 'Raissa.Pietersen@qiagen.com', 'Natalia Skupien, Stephanie Klauke', 'NET 30 DAYS', 'Yes', 'Stephanie Klauke', 'scanning.de@qiagen.com', 'QIAGEN GmbH Qiagen Strasse 1 40724 Hilden Germany', NULL),
    ('QIA003', 'QIA', 'Barbara Tajka-Zielonka', 'Barbara.Tajka-Zielonka@qiagen.com', 'Natalia Skupien, Stephanie Klauke', 'NET 30 DAYS', 'Yes', 'Stephanie Klauke', 'scanning.de@qiagen.com', 'QIAGEN GmbH Qiagen Strasse 1 40724 Hilden Germany', NULL),
    ('RAI001', 'RAI', 'Anastasia Potts', 'anastasia.potts@rainin.com', 'Meredith Swinehart', 'NET 60 DAYS', 'No', 'Anastasia Potts    Meredith Swinehart', 'anastasia.potts@rainin.com     meredith.swinehart@rainin.com', '7500 Edgewater Dr Oakland, CA 94621', NULL),
    ('SAR001', 'SAR', 'Jeanette Minshall', 'Jeanette.Minshall@Sartorius.com', 'Helge.Schnerr@sartorius.com', 'NET 30 DAYS', 'No', 'Helge Schnerr', 'Helge.Schnerr@sartorius.com', 'Sartorius AG Otto-Brenner-Str. 20 37079 Göttingen, Germany', NULL),
    ('SAR002', 'SAR', 'Kelsey Davis', 'kelsey.davis@sartorius.com', NULL, 'NET 30 DAYS', 'No', 'Kesley Davis', NULL, 'Sartorius Lab Instruments GmbH &  Co. KG Otto-Brenner- Straße 20 37079 Goettingen  Germany Kelsey Davis Campaign: LH Foundational LH Project Code: 7203553 Cost Center:22504312 GL: 739000 Campaign Manager: Kelsey Davis', 'Must include cost centre on the invoice'),
    ('SCA001', 'SCA', 'Amy Hamilton', 'amy.hamilton@scale.bio', 'Sheila Clark', 'NET 30 DAYS', 'No', 'Sheila Clark', 'Sheila.clark@scale.bio', '5601 Oberlin Dr. Suite 110 San Diego, CA 92121', NULL),
    ('TFS001', 'TFS', 'Rennae Hanson', 'rennae.hanson@thermofisher.com', 'Lailan Ghafur', 'NET 90 days', 'Yes (Coupa)', 'Accounts Payable', 'Invoices+NA@ThermoFisher.Coupahost.com', 'Life Technologies Corporation PO Box 1039 Carlsbad, CA 92008', NULL),
    ('TFS002', 'TFS', 'Ashkan Abbasian', 'ashkan.abbasian@thermofisher.com', NULL, 'NET 90 DAYS', 'Yes (Coupa)', 'Accounts Payable', 'Invoices+NA@ThermoFisher.Coupahost.com', 'Life Technologies Corporation PO Box 1039 Carlsbad, CA 92008', NULL),
    ('TFS003', 'TFS', 'Elizabeth Audiffred', 'elizabeth.audiffred@thermofisher.com', NULL, 'NET 90 DAYS', 'Yes (Coupa)', 'Accounts Payable', 'Invoices+NA@ThermoFisher.Coupahost.com', 'Life Technologies Corporation, PO Box 1039, Carlsbad, CA 92008', NULL),
    ('TFS004', 'TFS', 'Vishwadeepak Tripathi', 'deepak.tripathi@thermofisher.com', NULL, 'NET 90 DAYS', 'Yes (Coupa)', 'Accounts Payable', 'Invoices+NA@ThermoFisher.Coupahost.com', 'Life Technologies Corporation, PO Box 1039, Carlsbad, CA 92008', NULL),
    ('TFS005', 'TFS', 'Jonathon Laird', 'jonathon.laird@thermofisher.com', NULL, 'NET 90 DAYS', 'Yes (Coupa)', 'Thermo Fisher Scientific', 'Invoices+NA@ThermoFisher.Coupahost.com', 'Life Technologies Corporation, PO Box 1039, Carlsbad, CA 92008', NULL),
    ('TFS006', 'TFS', 'Selvi Selman', 'selvi.tamilselvam@thermofisher.com', NULL, 'NET 90 DAYS', 'Yes (Coupa)', NULL, NULL, NULL, 'Potential new client, details to be completed from IO'),
    ('TFS007', 'TFS', 'Hannah Mabus', 'hannah.mabus@thermofisher.com', 'Ryan Sasada - ryan.sasada@thermofisher.com', 'NET 90 DAYS', 'Yes (Coupa)', 'Accounts Payable', 'Invoices+NA@ThermoFisher.Coupahost.com', 'Life Technologies Corporation PO Box 1039 Carlsbad, CA 92008', NULL),
    ('TFS008', 'TFS', 'John McDonald', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
    ('TFS009', 'TFS', 'Chris Knowles', 'chris.knowles@thermofisher.com', 'Jennifer Burns - jennifer.burns@thermofisher.com  Matt Doig - matt.doig@thermofisher.com  Ali Hudson - alison.hudson@thermofisher.com', 'NET 90 DAYS', 'Yes - send by email, not coupa', 'Accounts Payable', 'Invoices+NA@ThermoFisher.Coupahost.com', '1400 North Point Parkway, Ste 10 West Palm Beach, FL 33412', NULL),
    ('TFS010', 'TFS', 'Rosy Manser', 'rosy.manser@thermofisher.com', 'eva.skacelova@thermofisher.com', 'NET 90 DAYS', 'Yes - send by email, not coupa', 'Accounts Payable', 'USHIL.APNA@thermofisher.com', 'Thermo Fisher Scientific, 5350 NE Dawson Creek Drive Hillsboro, OR 97124', NULL),
    ('TFS011', 'TFS', 'Sapna Padmanabhan', 'Sapna.Padmanabhan@thermofisher.com', NULL, 'NET 90 DAYS', 'Yes (Coupa)', 'Accounts Payable', 'Invoices+NA@thermofisher.coupahost.com.', 'Life Technologies Corporation PO Box 1039 Carlsbad, CA 92008', NULL),
    ('TFS012', 'TFS', 'Alejandra Sánchez-Eróstegui', 'Alejandra.Sanchez-Erostegui@thermofisher.com', NULL, 'NET 90 DAYS', 'No', 'Alejandra Sánchez-Eróstegui', 'Alejandra.Sanchez-Erostegui@thermofisher.com', '39, Rue d''Armagnac 33800 Bordeaux FRANCE', NULL),
    ('TGN001', 'TGN', 'Anastasiia Marchuk', 'anastasiia.marchuk@tissuegnostics.com', 'Rudolf Jedletzberger', 'NET 14 DAYS', 'No', 'Rudolf Jedletzberger', 'rudolf.jedletzberger@tissuegnostics.com', 'Taborstraße 10/2/8 1020 Vienna Austria', NULL),
    ('TOM001', 'TOM', 'Sumin Lee', 'slee@tomocube.com', NULL, 'NET 30 DAYS', 'No', 'Sumin Lee', 'slee@tomocube.com', '155 Sinseong-ro, 155 Sinseong-ro, Daejeon  34109, Republic of Korea', NULL),
    ('TWI001', 'TWI', 'Gemma Brils Garcia', 'gbrilsgarcia@twistbioscience.com', NULL, 'NET 14 DAYS', 'Yes', 'Gemma Brils Garcia or Emily Leproust', 'gbrilsgarcia@twistbioscience.com eleproust@twistbioscience.com', 'Twist Bioscience, 681 Gateway Blvd, South San Francisco, CA 94080', NULL),
    ('UNC001', 'UNC', 'Shannon Moore', 'shannon.moore@unchainedlabs.com', NULL, 'NET 14 DAYS', 'No', 'Shannon Moore', 'shannon.moore@unchainedlabs.com', '4747 Willow Rd., Pleasanton, CA, 94588', NULL),
    ('VEB001', 'VEB', 'Dan Croucher, PhD', 'danielcroucher@vectorbuilder.com', 'Grecia Perez', 'NET 14 DAYS', 'No', 'Grecia Perez', 'greciaperez@vectorbuilder.com', 'VectorBuilder Inc, 1010 W. 35th Street, Suite 515, Chicago IL 60609', NULL),
    ('VLT001', 'VLT', 'Kim Miller', 'kmiller@voltalabs.co', NULL, NULL, NULL, NULL, NULL, NULL, 'Add additional details once IO signed'),
    ('WAS001', 'WAS', 'Matej Metkovic', 'matej@wasteless.bio', NULL, NULL, NULL, NULL, NULL, NULL, 'Add additional details required, free webinar in first instance'),
    ('YOK001', 'YOK', 'Kevin Jan', 'Kevin.Jan@yokogawa.com', 'Mai Hagimoto, Esther Kiesermann', 'NET 30 days', 'No', 'Mai Hagimoto', 'mai.hagimoto@yokogawa.com', '2-9-32 Nakacho, Musashino, Tokyo, Japan 180-8750', NULL),
    ('ZEI001', 'ZEI', 'Sreenivas Bhattiprolu', 'sreenivas.bhattiprolu@zeiss.com', 'Christoph Schönhal, Eva Opferkuch, Theresa Schatt', 'NET 30 DAYS', 'Yes', 'Christoph Schönhal', 'invoice@zeiss.com', 'MIG Produktion, Königsallee 9 - 21, 37081 Göttingen', NULL),
    ('ZEI002', 'ZEI', 'Anke Koenen', 'anke.koenen@zeiss.com', 'Karin Enderle', 'NET 30 DAYS', 'Yes', 'Karin Enderle', 'karin.enderle.ext@zeiss.com', 'c/o Kontinent Spedition GmbH Bollberg Im Gewerbepark 3 07646 STADTRODA GERMANY', NULL),
    ('ZEI003', 'ZEI', NULL, NULL, NULL, 'NET 30 DAYS', 'Yes', 'ZEISS Microscopy', 'invoice@zeiss.com', 'Carl Zeiss Microscopy GmbH Carl-Zeiss-Promenade 10 07745 Jena', 'FREE TO BE USED'),
    ('ZEI004', 'ZEI', 'Daniel Hartmann', 'daniel.hartmann@zeiss.com', 'Theresa Schatt', 'NET 30 DAYS', 'Yes', 'Accounts Department', 'invoice@zeiss.com', 'Carl Zeiss Microscopy GmbH c/o Carl Zeiss Shared Services Sp. z o.o. ul. Abpa A. Baraniaka 88E 61-131 Poznan - POLAND', NULL),
    ('ZYM001', 'ZYM', 'Karen Kao', 'kkao@zymoresearch.com', NULL, 'NET 14 DAYS', 'No', 'Karen Kao', 'kkao@zymoresearch.com', '2911 Dow Ave Tustin, California 92780 United States', NULL),
    ('ZYM002', 'ZYM', 'Joshua Lo', 'jlo@zymoresearch.com', 'Osman Mir', 'NET 14 DAYS', 'No', 'Account Payable', 'ap@zymoresearch.com', '17062 Murphy Avenue, Irvine, CA 92614, USA', NULL),
    ('ZYM003', 'ZYM', 'Diana Jia', 'DJia@zymoresearch.com', 'Phuong Nguyen, Luigi Basillo, Nora Beik, Yi Xu', 'NET 14 DAYS', 'No', 'Phuong Nguyen', 'ap@zymoresearch.com', '2911 Dow Ave, Tustin, CA 92780', NULL),
    ('ZYM004', 'ZYM', 'Julia Rietsche', 'jrietsche@zymoresearch.de', 'Tamaris Worner,', 'NET 14 DAYS', 'No', 'Accounts Payable', 'invoice@zymoresearch.de', 'Zymo Research Europe GmbH, Muelhauser Str. 9, 79110 Freiburg im Breisgau, Germany', NULL)
) AS v(
    bsb_client_code, tla,
    primary_contact, primary_contact_email,
    other_people, payment_terms, po_required,
    billing_contact, billing_email, billing_address, notes
)
JOIN clients c ON c.tla = v.tla;
