-- Migration: io_products table + upsert_io_product function
-- Run on Sevalla via SQL studio (paste each block separately)
-- 2026-02-25

-- ============================================
-- BLOCK 1: Create io_products table
-- ============================================

CREATE TABLE io_products (
    id                  SERIAL PRIMARY KEY,
    io_reference        VARCHAR(255) NOT NULL,  -- loose ref to insertion_orders(io_reference); no FK to avoid type mismatch
    product_type        TEXT NOT NULL,
    product_name        TEXT,                   -- often empty from form; nullable by design
    unique_id           TEXT UNIQUE NOT NULL,   -- EVENT-{IO Ref}-{UUID}, generated by Make.com
    drive_folder_id     TEXT,                   -- IO folder ID (Tier 5); populated during Drive creation
    asana_project_id    TEXT,                   -- populated when per-product Asana creation is built
    created_at          TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_io_products_io_reference ON io_products(io_reference);

-- ============================================
-- BLOCK 2: upsert_io_product function
-- Paste and run alone in Sevalla SQL studio
-- ============================================

CREATE OR REPLACE FUNCTION upsert_io_product(
    p_io_reference      TEXT,
    p_product_type      TEXT,
    p_product_name      TEXT DEFAULT NULL,
    p_unique_id         TEXT DEFAULT NULL,
    p_drive_folder_id   TEXT DEFAULT NULL
) RETURNS INTEGER AS $fn$
DECLARE
    v_id INTEGER;
BEGIN
    INSERT INTO io_products (
        io_reference,
        product_type,
        product_name,
        unique_id,
        drive_folder_id
    )
    VALUES (
        p_io_reference,
        p_product_type,
        NULLIF(TRIM(COALESCE(p_product_name, '')), ''),
        p_unique_id,
        p_drive_folder_id
    )
    ON CONFLICT (unique_id) DO UPDATE SET
        drive_folder_id  = COALESCE(EXCLUDED.drive_folder_id, io_products.drive_folder_id),
        product_name     = COALESCE(NULLIF(TRIM(EXCLUDED.product_name), ''), io_products.product_name)
    RETURNING id INTO v_id;

    RETURN v_id;
END;
$fn$ LANGUAGE plpgsql;
